=== Nv4n/FMI/2024-2025/xml-technologies/agro-nursery-warehouse/warehouses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="warehouses">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="warehouse" minOccurs="1" maxOccurs="unbounded" type="Warehouse"/>
                <xsd:element name="company">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="contact" type="Contact"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Warehouse">
        <xsd:sequence>
            <xsd:element name="products">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="product" type="Product" minOccurs="1"
                                     maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="contact" type="Contact"/>
            <xsd:element name="deliveries">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="delivery" type="Delivery" minOccurs="0"
                                     maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Delivery">
        <xsd:sequence>
            <xsd:element name="products">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="product" type="Product" minOccurs="1"
                                     maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="contact" type="Contact"/>
        </xsd:sequence>
        <xsd:attribute name="status" default="pending">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="canceled"/>
                    <xsd:enumeration value="returned"/>
                    <xsd:enumeration value="pending"/>
                    <xsd:enumeration value="finished"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cost" type="xsd:double"/>
    </xsd:complexType>

    <xsd:complexType name="Contact">
        <xsd:all>
            <xsd:element name="location" minOccurs="1" maxOccurs="1" type="Location"/>
            <xsd:element name="email" minOccurs="0" type="xsd:string"/>
            <xsd:element name="phone" minOccurs="0" type="xsd:string"/>
        </xsd:all>
    </xsd:complexType>

    <xsd:complexType name="Location">
        <xsd:sequence>
            <xsd:element name="country" type="xsd:string"/>
            <xsd:element name="city" type="xsd:string"/>
            <xsd:element name="address" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Product">
        <xsd:sequence>
            <xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="info" type="ContentInfo"/>
        </xsd:sequence>
        <xsd:attribute name="price" type="xsd:double" use="required"/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="quantity" type="xsd:int" use="required"/>

    </xsd:complexType>

    <xsd:complexType name="ContentInfo">
        <xsd:sequence>
            <xsd:element name="fragile" type="xsd:boolean" minOccurs="0" maxOccurs="1"
                         default="false"/>
            <xsd:element name="weight" type="xsd:double"/>
            <xsd:element name="expiry_date" type="xsd:date"/>
            <xsd:element name="type">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="tool"/>
                        <xsd:enumeration value="seeds"/>
                        <xsd:enumeration value="clothing"/>
                        <xsd:enumeration value="equipment"/>
                        <xsd:enumeration value="structure"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

        <!--Всеки
        студент избира и разработва собствен модел на документ за избраната
        от него и одобрена от асистиращите приложна област. За този модел се
        съставя Document Type Definition - DTD или SCHEMA. DTD или SCHEMA
        трябва да съдържа минимум 20 различни елемента и 5 атрибута, с които се
        задава състава и структурата на модела. В документа трябва да има поне две
        различни групи вложени елементи (всяка с най-малко 3 елемента). Групите
        трябва да се срещат 2-3 пъти
        -->

=== Nv4n/FMI/2024-2025/xml-technologies/agro-nursery-warehouse/public/example1733442569258.xml
<?xml version="1.0" encoding="UTF-8"?>
<warehouses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="warehouses.xsd">
    <owner>
        <name>Агро магазин Любо Цветков</name>
        <contact>
            <location>
                <country>Черна гора</country>
                <city>Подгорица</city>
                <address>ул. Независимост 12</address>
            </location>
            <phone>+502 33-141-382</phone>
        </contact>
    </owner>
    <warehouse>
        <products>
            <product name="трактор" brand="Машиникс">
                <info>
                    <fragile>false</fragile>
                    <price currency="USD">150000</price>
                    <quantity>5</quantity>
                    <weight unit="kg">1500</weight>
                    <expiry_date>2032-05-25</expiry_date>
                    <type>equipment</type>
                </info>
                <notes>идеален за средни площи</notes>
            </product>
            <product name="косачка за трева" brand="ТехноФермер">
                <info>
                    <fragile>false</fragile>
                    <price currency="USD">150</price>
                    <quantity>25</quantity>
                    <weight unit="kg">10</weight>
                    <expiry_date>2032-08-05</expiry_date>
                    <type>equipment</type>
                </info>
                <notes>идеална за малки и средни градини</notes>
            </product>
        </products>
        <contact>
            <location>
                <country>Северна Македония</country>
                <city>Скопие</city>
                <address>бул. Македония 15</address>
            </location>
            <email>warehouse_lyubo_zlatev824@gmail.com</email>
            <phone>+004 30-483-45203</phone>
        </contact>
        <deliveries>
            <delivery status="canceled" cost="5867.51">
                <products>
                    <product name="семена пепино пъпеш" brand="Градинар">
                        <info>
                            <fragile>false</fragile>
                            <price currency="RON">12.99</price>
                            <quantity>14</quantity>
                            <weight unit="g">0.9</weight>
                            <expiry_date>2030-04-10</expiry_date>
                            <type>seeds</type>
                        </info>
                        <notes>медено сладък сорт</notes>
                    </product>
                    <product name="ръкавици за градинарство" brand="ГрадинаПро">
                        <info>
                            <fragile>false</fragile>
                            <price currency="BGN">7.99</price>
                            <quantity>23</quantity>
                            <weight unit="kg">0.2</weight>
                            <expiry_date>2027-06-10</expiry_date>
                            <type>clothing</type>
                        </info>
                        <notes>за защита от остри предмети</notes>
                    </product>
                    <product name="поливна система" brand="Водаградин">
                        <info>
                            <fragile>false</fragile>
                            <price currency="BGN">180</price>
                            <quantity>29</quantity>
                            <weight unit="kg">10</weight>
                            <expiry_date>2030-10-01</expiry_date>
                            <type>equipment</type>
                        </info>
                        <notes>лесна за настройка и използване</notes>
                    </product>
                </products>
                <vendor>
                    <name>Борислав Филипов</name>
                    <contact>
                        <location>
                            <country>Румъния</country>
                            <city>Брашов</city>
                            <address>ул. Република 11</address>
                        </location>
                        <email>borislav_filipov941@abv.bg</email>
                    </contact>
                </vendor>
            </delivery>
        </deliveries>
    </warehouse>
    <warehouse>
        <products>
            <product name="ръкавици за градинарство" brand="ГрадинаПро">
                <info>
                    <fragile>false</fragile>
                    <price currency="BGN">7.99</price>
                    <quantity>20</quantity>
                    <weight unit="kg">0.2</weight>
                    <expiry_date>2027-06-10</expiry_date>
                    <type>clothing</type>
                </info>
                <notes>за защита от остри предмети</notes>
            </product>
            <product name="джобен нож" brand="ФермерОборудване">
                <info>
                    <fragile>false</fragile>
                    <price currency="BGN">12.5</price>
                    <quantity>17</quantity>
                    <weight unit="kg">0.5</weight>
                    <expiry_date>2050-07-10</expiry_date>
                    <type>tool</type>
                </info>
                <notes>за многофункционално използване</notes>
            </product>
            <product name="трактор" brand="Машиникс">
                <info>
                    <fragile>false</fragile>
                    <price currency="USD">150000</price>
                    <quantity>14</quantity>
                    <weight unit="kg">1500</weight>
                    <expiry_date>2032-05-25</expiry_date>
                    <type>equipment</type>
                </info>
                <notes>идеален за средни площи</notes>
            </product>
        </products>
        <contact>
            <location>
                <country>България</country>
                <city>Пловдив</city>
                <address>ул. Главна 67</address>
            </location>
            <phone>+424 52-075-23436</phone>
        </contact>
        <deliveries>
            <delivery status="pending" cost="688.5">
                <products>
                    <product name="лопата" brand="АгроИнструмент">
                        <info>
                            <fragile>false</fragile>
                            <price currency="BGN">25.5</price>
                            <quantity>27</quantity>
                            <weight unit="kg">2.3</weight>
                            <expiry_date>2028-01-15</expiry_date>
                            <type>tool</type>
                        </info>
                        <notes>подходяща за градинска работа</notes>
                    </product>
                </products>
                <vendor>
                    <name>Тодор Златев</name>
                    <contact>
                        <location>
                            <country>Черна гора</country>
                            <city>Подгорица</city>
                            <address>ул. Независимост 12</address>
                        </location>
                        <phone>+280 473-684-562</phone>
                    </contact>
                </vendor>
            </delivery>
            <delivery status="returned" cost="8141.12">
                <products>
                    <product name="градски ботуши" brand="ТехноОбувки">
                        <info>
                            <fragile>false</fragile>
                            <price currency="BGN">45</price>
                            <quantity>1</quantity>
                            <weight unit="kg">1.5</weight>
                            <expiry_date>2032-02-20</expiry_date>
                            <type>clothing</type>
                        </info>
                        <notes>удобни и издръжливи при всякакви условия</notes>
                    </product>
                    <product name="косачка за трева" brand="ТехноФермер">
                        <info>
                            <fragile>false</fragile>
                            <price currency="USD">150</price>
                            <quantity>27</quantity>
                            <weight unit="kg">10</weight>
                            <expiry_date>2032-08-05</expiry_date>
                            <type>equipment</type>
                        </info>
                        <notes>идеална за малки и средни градини</notes>
                    </product>
                    <product name="семена пепино пъпеш" brand="Градинар">
                        <info>
                            <fragile>false</fragile>
                            <price currency="RON">12.99</price>
                            <quantity>17</quantity>
                            <weight unit="g">0.9</weight>
                            <expiry_date>2030-04-10</expiry_date>
                            <type>seeds</type>
                        </info>
                        <notes>медено сладък сорт</notes>
                    </product>
                </products>
                <vendor>
                    <name>Любо Радев</name>
                    <contact>
                        <location>
                            <country>Хърватия</country>
                            <city>Загреб</city>
                            <address>ул. Илица 45</address>
                        </location>
                        <email>lyubo_radev1682@gmail.com</email>
                        <phone>+733 465-810-27161</phone>
                    </contact>
                </vendor>
            </delivery>
        </deliveries>
    </warehouse>
</warehouses>

=== Nv4n/FMI/2024-2025/xml-technologies/agro-nursery-warehouse/transformations/xml-output2.xml
<?xml version="1.0" encoding="UTF-8"?><warehouses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../public/warehouses.xsd">
    <owner>
        <name>Агро магазин Владимир Огнянов</name>
        <contact>
            <location>
                <country>Словения</country>
                <city>Марибор</city>
                <address>ул. Главен площад 4</address>
            </location>
            <email>agro_magazin_vladimir_ognyanov1009@outlook.com</email>
        </contact>
    </owner>
    <warehouse>
        <products>
            <product name="трактор" brand="Машиникс">
                <info>
                    <price currency="USD">150000</price>
                    <quantity>24</quantity>
                    <weight unit="kg">1500</weight>
                    <expiry_date>2032-05-25</expiry_date>
                    <type>equipment</type>
                </info>
            </product>
            <product name="лопата" brand="АгроИнструмент">
                <info>
                    <price currency="BGN">25.5</price>
                    <quantity>12</quantity>
                    <weight unit="kg">2.3</weight>
                    <expiry_date>2028-01-15</expiry_date>
                    <type>tool</type>
                </info>
            </product>
        </products>
        <contact>
            <location>
                <country>Сърбия</country>
                <city>Белград</city>
                <address>бул. Краля Александра 25</address>
            </location>
            <email>warehouse_mariya_todorova1239@yahoo.com</email>
        </contact>
        <deliveries/>
    </warehouse>
</warehouses>

=== Nv4n/FMI/2024-2025/xml-technologies/agro-nursery-warehouse/warehouses.xml
<?xml version="1.0" encoding="UTF-8"?>
<warehouses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="warehouses.xsd">
    <warehouse>
        <products>
            <product brand="Семена Гешев" price="1" name="Домати" quantity="34">
                <info>
                    <fragile>false</fragile>
                    <weight>0.1</weight>
                    <expiry_date>2025-09-24</expiry_date>
                    <type>seeds</type>
                </info>
                <notes>Keep in dry place</notes>
            </product>
            <product name="Круши Гергана" brand="Семена Фермера" price="2.5" quantity="30">
                <info>
                    <fragile>true</fragile>
                    <weight>1</weight>
                    <expiry_date></expiry_date>
                    <type>tool</type>
                </info>
            </product>
        </products>
        <contact>
            <location>
                <country>Bulgaria</country>
                <city>Sofia</city>
                <address>ul.Pencho 1</address>
            </location>
            <phone>+35988-88-77-7777</phone>
        </contact>
        <deliveries>
            <delivery>
                <products>
                    <product brand="Семена Гешев" price="1" name="Домати" quantity="10">
                        <info>
                            <fragile>false</fragile>
                            <weight>0.2</weight>
                            <expiry_date>2027-12-13</expiry_date>
                            <type>seeds</type>
                        </info>
                    </product>
                </products>
                <vendor>
                    <name>Vendors inc.</name>
                    <contact>
                        <location>
                            <country>Bulgaria</country>
                            <city>Sofia</city>
                            <address>ul. Gosho Geshev 34</address>
                        </location>
                        <email>pencho@penchev.com</email>
                        <phone>+73-444-23-44</phone>
                    </contact>
                </vendor>
            </delivery>
        </deliveries>
    </warehouse>
    <company>
        <name>Agro Nursery inc</name>
        <contact>
            <location>
                <country>Bulgaria</country>
                <city>Sofia</city>
                <address>ul.Pencho 1</address>
            </location>
            <email>gosho@gosho.com</email>
        </contact>
    </company>
</warehouses>
